[package]
name = "rustdsp"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4.4"
rand = "0.8.5"
anyhow = "1.0.75"
rustfft = "6.1.0"
bytes = "1.5.0"
rand_distr = "0.4.3"
once_cell = "1.18.0"
lazy_static = "1.4.0"


[dev-dependencies]
criterion = "0.5.1"
plotters = "0.3.3"

[[bench]]
name = "full_bench"
harness = false

[[bench]]
name = "qpsk"
harness = false

[[bench]]
name = "bpsk"
harness = false

[[bench]]
name = "fsk"
harness = false

[[bench]]
name = "ask"
harness = false