[package]
name = "superdsp"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Standard
bladerf-bindings = "0.0.13"
num-complex = "0.4.6"
rustfft = "6.2.0"